{{- if .Values.vault_settings.gcp_secret_manager }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.csi_default_name }}
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-db-host/versions/latest" 
        fileName: "database-host"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-classification-db-user/versions/latest" 
        fileName: "classification-db-user"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-classification-db-password/versions/latest" 
        fileName: "classification-db-password"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-classification-db/versions/latest" 
        fileName: "classification-db"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/message-broker-driver/versions/latest" 
        fileName: "message-broker-driver"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-message-broker-connection-string/versions/latest" 
        fileName: "message-broker-connection-string"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-app-secret-key/versions/latest" 
        fileName: "app-secret-key"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/keycloak-certs-endpoint/versions/latest" 
        fileName: "keycloak-certs-endpoint"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/aws-access-key-id/versions/latest" 
        fileName: "aws-access-key-id"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/aws-secret-access-key/versions/latest" 
        fileName: "aws-secret-access-key"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/azure-connection-string/versions/latest" 
        fileName: "azure-connection-string"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/azure-container-name/versions/latest" 
        fileName: "azure-container-name"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/gcp-api-key/versions/latest" 
        fileName: "gcp-api-key"
  secretObjects:
    - secretName: {{ .Values.secrets.deps_classification.secretName }}
      type: Opaque
      data:
      - objectName: "keycloak-certs-endpoint"
        key: keycloak-certs-endpoint
      - objectName: "app-secret-key"
        key: app-secret-key
      - objectName: "message-broker-connection-string"
        key: message-broker-connection-string
      - objectName: "message-broker-driver"
        key: message-broker-driver
      - objectName: "database-host"
        key: database-host
      - objectName: "classification-db-user"
        key: user
      - objectName: "classification-db-password"
        key: password
      - objectName: "classification-db"
        key: database-db
      - objectName: "aws-access-key-id"
        key: aws-access-key-id
      - objectName: "aws-secret-access-key"
        key: aws-secret-access-key
      - objectName: "azure-connection-string"
        key: azure-connection-string
      - objectName: "azure-container-name"
        key: azure-container-name
      - objectName: "gcp-api-key"
        key: gcp-api-key
{{- end }}
