secrets:
  deps_classification:
    secretName: deps-classification
  app_secret_key:
    secretName: app-secret-key
  classification_database:
    secretName: classification-database
  keycloak_certs_endpoint:
    secretName: keycloak-certs-endpoint
  common_secret:
    secretName: common-secret
  rabbitmq_password:
    secretName: rabbitmq-password
  security_certs:
    secretName: security-certs
  redis_password:
    secretName: redis-password
  kafka_secrets:
    secretName: kafka-secrets
  database_ssl_secret:
    secretName: database-ssl-secret
  telemetry_secrets:
    secretName: telemetry-secrets

helm_logs_job:
  serviceAccountName: gitlab-ci
  image:
    path: "/base/kubernetes-helm"
    pullPolicy: IfNotPresent
    tag: "0.1.1"
  resources: {}

registry: ""
env: ""

classification:
  replicaCount: 1
  image:
    path: "/deps-dev-x01/deps-classification"
    pullPolicy: IfNotPresent
    tag: ""
  imagePullSecrets: artifactory
  service:
    type: ClusterIP
    port: 8000
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

classification_consumer:
  replicaCount: 1
  image:
    path: '/deps-dev-x01/deps-classification'
    pullPolicy: IfNotPresent
    tag: ''
  imagePullSecrets: artifactory
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

certs_location:
  certs_default_path: "/tmp/ssl"
  database_sslcerts_path: "/home/dbcerts"

classification_settings:
  ENV: dev

  DATABASE_PORT: '5432'
  DATABASE_DRIVER: psycopg2
  DATABASE_DIALECT: postgresql
  DATABASE_REQUIRE_SECURE_TRANSPORT: false
  DATABASE_SSLKEY_PATH: "/home/dbcerts/tls.key"
  DATABASE_SSLCERT_PATH: "/home/dbcerts/tls.crt"
  DATABASE_SSLROOTCERT_PATH: "/home/dbcerts/root.crt"

  FILE_STORAGE_URL: "http://file-storage:8004"
  AI_FUSION_URL: 'http://ai-fusion:8000'
  AI_FUSION_TIMEOUT: 300
  GEN_AI_GROUPING_FACTOR: 4

  AUTH_VERIFY_SSL: false

  LOG_LEVEL: "INFO"
  DOCUMENTATION_ENABLED: "true"

  RABBITMQ_TLS_ENABLED: false

  KAFKA_GROUP_ID: classification
  KAFKA_AUTO_OFFSET_RESET: earliest
  KAFKA_SECURITY_ENABLED: false

  # Azure Service Bus
  ASB_SUBSCRIPTION_STRATEGY: 'no_preparation'

  # Telemetry
  INSTRUMENTATION_ENABLED: false
  SERVICE_NAME: classification
  EXPORTER_TYPE: azure

  # Object storage
  OBJECT_STORAGE_MODE: "sync"
  OBJECT_STORAGE_TYPE: "file-storage"
  # aws
  S3_BUCKET_NAME: bucket_name
  S3_ENDPOINT_URL: https://s3.us-east-1.amazonaws.com
  # gcp
  GCP_BLOB_STORAGE_BUCKET_NAME: "bucket_name"

helm:
  helm_logs_job_enabled: false

message_broker_asb_without_manage_permission:
  enabled: false

csi:
  csi_default_name: deps-classification
  vault_namespace: 'k8s-dev'
  roleName: 'k8s-dev'
  vaultKubernetesMountPath: 'kubernetes-dev'

secrets_location:
  secrets_default_path: "/mnt/secrets-store"

service_account:
  serviceAccountName: 'deps-develop'

azure_kv_settings:
  keyvaultName: ""
  tenantId: ""
  userAssignedIdentityID: ""
  resourceGroup: ""
  subscriptionId: ""

vault_settings:
  enabled: false
  hashicorp_vault: false
  azure_key_vault: false
  gcp_secret_manager: false
  aws_secret_manager: false
  aws_secret_manager_region: ''

classification_vault_enabled:
  env:
  - name: AUTH_CERTS_ENDPOINT
    valueFrom:
      secretKeyRef:
        name: deps-classification
        key: keycloak-certs-endpoint
  - name: MESSAGING_DRIVER
    valueFrom:
      secretKeyRef:
        name: deps-classification
        key: message-broker-driver
  - name: MESSAGE_BROKER_CONNECTION_STRING
    valueFrom:
      secretKeyRef:
        name: deps-classification
        key: message-broker-connection-string
  - name: DATABASE_HOST
    valueFrom:
      secretKeyRef:
        name: deps-classification
        key: database-host
  - name: DATABASE_DB
    valueFrom:
      secretKeyRef:
        name: deps-classification
        key: database-db
  - name: DATABASE_USER
    valueFrom:
      secretKeyRef:
        name: deps-classification
        key: user
  - name: DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: deps-classification
        key: password
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: deps-classification
        key: aws-access-key-id
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: deps-classification
        key: aws-secret-access-key
  - name: AZURE_CONNECTION_STRING
    valueFrom:
      secretKeyRef:
        name: deps-classification
        key: azure-connection-string
  - name: AZURE_CONTAINER_NAME
    valueFrom:
      secretKeyRef:
        name: deps-classification
        key: azure-container-name
  - name: GCP_BLOB_STORAGE_AUTH_KEY
    valueFrom:
      secretKeyRef:
        name: deps-classification
        key: gcp-api-key

classification_vault_disabled:
  env:
  - name: AUTH_CERTS_ENDPOINT
    valueFrom:
      secretKeyRef:
        name: keycloak-certs-endpoint
        key: keycloak-certs-endpoint
  - name: MESSAGING_DRIVER
    valueFrom:
      secretKeyRef:
        name: common-secret
        key: message-broker-driver
  - name: MESSAGE_BROKER_CONNECTION_STRING
    valueFrom:
      secretKeyRef:
        name: common-secret
        key: message-broker-connection-string
  - name: DATABASE_HOST
    valueFrom:
      secretKeyRef:
        name: common-secret
        key: database-host
  - name: DATABASE_DB
    valueFrom:
      secretKeyRef:
        name: classification-database
        key: database-db
  - name: DATABASE_USER
    valueFrom:
      secretKeyRef:
        name: classification-database
        key: user
  - name: DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: classification-database
        key: password
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: file-storage-aws-credentials
        key: aws-access-key-id
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: file-storage-aws-credentials
        key: aws-secret-access-key
  - name: AZURE_CONNECTION_STRING
    valueFrom:
      secretKeyRef:
        name: azure-blob-storage
        key: azure-connection-string
  - name: AZURE_CONTAINER_NAME
    valueFrom:
      secretKeyRef:
        name: azure-blob-storage
        key: azure-container-name
  - name: GCP_BLOB_STORAGE_AUTH_KEY
    valueFrom:
      secretKeyRef:
        name: gcp-credentials
        key: gcp-api-key

classification_consumer_vault_enabled:
  env:
  - name: SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: deps-classification
        key: app-secret-key
  - name: AUTH_CERTS_ENDPOINT
    valueFrom:
      secretKeyRef:
        name: deps-classification
        key: keycloak-certs-endpoint
  - name: MESSAGING_DRIVER
    valueFrom:
      secretKeyRef:
        name: deps-classification
        key: message-broker-driver
  - name: MESSAGE_BROKER_CONNECTION_STRING
    valueFrom:
      secretKeyRef:
        name: deps-classification
        key: message-broker-connection-string
  - name: DATABASE_HOST
    valueFrom:
      secretKeyRef:
        name: deps-classification
        key: database-host
  - name: DATABASE_DB
    valueFrom:
      secretKeyRef:
        name: deps-classification
        key: database-db
  - name: DATABASE_USER
    valueFrom:
      secretKeyRef:
        name: deps-classification
        key: user
  - name: DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: deps-classification
        key: password
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: deps-classification
        key: aws-access-key-id
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: deps-classification
        key: aws-secret-access-key
  - name: AZURE_CONNECTION_STRING
    valueFrom:
      secretKeyRef:
        name: deps-classification
        key: azure-connection-string
  - name: AZURE_CONTAINER_NAME
    valueFrom:
      secretKeyRef:
        name: deps-classification
        key: azure-container-name
  - name: GCP_BLOB_STORAGE_AUTH_KEY
    valueFrom:
      secretKeyRef:
        name: deps-classification
        key: gcp-api-key

classification_consumer_vault_disabled:
  env:
  - name: SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: app-secret-key
        key: app-secret-key
  - name: AUTH_CERTS_ENDPOINT
    valueFrom:
      secretKeyRef:
        name: keycloak-certs-endpoint
        key: keycloak-certs-endpoint
  - name: MESSAGING_DRIVER
    valueFrom:
      secretKeyRef:
        name: common-secret
        key: message-broker-driver
  - name: MESSAGE_BROKER_CONNECTION_STRING
    valueFrom:
      secretKeyRef:
        name: common-secret
        key: message-broker-connection-string
  - name: DATABASE_HOST
    valueFrom:
      secretKeyRef:
        name: common-secret
        key: database-host
  - name: DATABASE_DB
    valueFrom:
      secretKeyRef:
        name: classification-database
        key: database-db
  - name: DATABASE_USER
    valueFrom:
      secretKeyRef:
        name: classification-database
        key: user
  - name: DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: classification-database
        key: password
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: file-storage-aws-credentials
        key: aws-access-key-id
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: file-storage-aws-credentials
        key: aws-secret-access-key
  - name: AZURE_CONNECTION_STRING
    valueFrom:
      secretKeyRef:
        name: azure-blob-storage
        key: azure-connection-string
  - name: AZURE_CONTAINER_NAME
    valueFrom:
      secretKeyRef:
        name: azure-blob-storage
        key: azure-container-name
  - name: GCP_BLOB_STORAGE_AUTH_KEY
    valueFrom:
      secretKeyRef:
        name: gcp-credentials
        key: gcp-api-key
